### ISSUE TITLE
Action does not respect the job's `working-directory`

### ISSUE THREAD

**Issue by jbstewart** [chkfung/android-version-actions#11]
Thanks for this great action! 

My problem is that the job that includes this action has the following properties set for the job (it's a monorepo with servers, web apps and several Android apps):
```
    defaults:
      run:
        working-directory: ./Apps/Android/Root
```
When I try to use the action:
```
      - name: + Bump Android App #1 version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app-one/build.gradle
          versionCode: ${{ env.ANDROID_BUILD_CODE }}
```
the action fails, but if I change it to:
```
      - name: + Bump Android App #1 version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: Apps/Android/Root/app-one/build.gradle
          versionCode: ${{ env.ANDROID_BUILD_CODE }}
```
then the action works correctly.

PROBLEM: The action should respect the job's `working-directory`.
