### ISSUE TITLE
BuildConfig.VERSION_CODE is still set to default value.

### ISSUE THREAD

**Issue by dtokar-pcty** [chkfung/android-version-actions#12]
Hello,

I want to show the current build version code on the login screen of my application. I am showing the BuildConfig.VERSION_CODE to get the value, but it is still set to default value and is not overridden during build of the apk on Github:
 
```
Row {
        Text(text = "App version: ${BuildConfig.VERSION_CODE}")
}
```

I am using this to increment the version code in github action workflow, which works fine and the version code is incremented:

```
- name: Set version code and version name
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: app_1.0.0_${{github.run_number}}
```

Thank you.
