### ISSUE TITLE
`app/build.gradle` does not seem to get updated

### ISSUE THREAD

**Issue by ronaldwolvers** [chkfung/android-version-actions#2]
Hi! I would like to use this plug-in to update our `versionCode` and `versionName` using GitHub Actions, but I do not seem to be getting any results. I am new to using GitHub actions, and so I could be doing something wrong. The file I created is `.github/workflows/android-version-action.yml` and looks like this:

```
name: Bump the version code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle # or app/build.gradle.kts 
          versionCode: ${{github.run_number}}
          versionName: 1.0.0
```

This is the output of the "Bump version" step in the workflow:

```
Run chkfung/android-version-actions@v1.1
  with:
    gradlePath: app/build.gradle
    versionCode: 4
    versionName: 1.0.0
  env:
    JAVA_HOME_8.0.302_x64: /opt/hostedtoolcache/jdk/8.0.302/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.302/x64
    JAVA_HOME_8_0_302_X64: /opt/hostedtoolcache/jdk/8.0.302/x64
Gradle Path : app/build.gradle
Version Code : 4
Version Name : 1.0.0
Successfully override version code 4
Successfully override version code 1.0.0
```

I would expect the `build.gradle` file to contain `versionCode` 4 and `versionName` 1.0.0 but nothing seems to have happened. Thanks for making this plug-in and I appreciate any help or support!

**Comment by chkfung** [comment]
Hi, would like to check is the output apk updated with the new version code and version name?
can check with this command
```
$ANDROID_HOME/build-tools/28.0.3/aapt dump badging app/build/outputs/apk/app.apk
```

**Comment by ronaldwolvers** [comment]
Hi! I ran the command and the output was:

`package: name='com.example.app' versionCode='5' versionName='1.0' compileSdkVersion='30' compileSdkVersionCodename='11'`

5 and 1.0 are the values that I specified in the `build.gradle` file.

**Comment by chkfung** [comment]
yap that sounds good, 
this plugin is to override the version code and version name without making changes to the repository code, it will not update `build.gradle` file

**Comment by ronaldwolvers** [comment]
Understood! I was wondering; where would the APK be located? We currently don't upload our builds to any hosting server, so I'm not sure where to find the APK that has the updated `versionCode` and `versionName`. Thanks again for making this plugin!

**Comment by chkfung** [comment]
You will need another plugin to upload the apk to the github action storage and download it from the action dashboard
Github Action Upload Plugin : https://github.com/marketplace/actions/upload-a-build-artifact

Attached a sample workflow snippet for your reference
```
    - name: Bump version
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle.kts
        versionCode: ${{github.run_number}}
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: debug-${{github.run_number}}.apk # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: app/build/outputs/apk/debug/*.apk
```

**Comment by ronaldwolvers** [comment]
Thank you so much @chkfung ! I will give this a try shortly!

**Comment by ronaldwolvers** [comment]
Hey @chkfung ! I was able to use your plug-in successfully! For reference, this is the YAML file that I used, and which uploaded an .APK file to GitHub successfully:

```
name: Bump the version code and upload an APK file
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: 1.0.0
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: app-debug_${{github.run_number}}.apk # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: app/build/outputs/apk/debug/*.apk
```

Awesome work! My team will be very happy!
