### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by eatyan** [chkfung/android-version-actions#6]
Using following code:
```
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: 1.0.8
```

Failing with following error message:

**Run chkfung/android-version-actions@v1.1
Gradle Path : app/build.gradle
Version Code : 17
Version Name : 1.0.8
/home/runner/work/_actions/chkfung/android-version-actions/v1.1/index.js:21
            newGradle = newGradle.replace(versionCodeRegexPattern, `$1$***versionCode***`);
                                  ^

TypeError: Cannot read property 'replace' of undefined
    at ReadFileContext.callback (/home/runner/work/_actions/chkfung/android-version-actions/v1.1/index.js:21:35)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:[13](https://github.com/eatyan/mobile/runs/8259245144?check_suite_focus=true#step:6:14))**
